### ISSUE TITLE
`last_knowledge_of_server` and other optional arguments should have `Option<_>` types

### ISSUE THREAD

**Issue by borsboom** [doy/ynab-api#1]
Many of the API endpoints have a `last_knowledge_of_server` argument.  According to the documentation (e.g. [TransactionsApi.get_transactions](https://github.com/doy/ynab-api/blob/4c94e5f9101c14bfc5c6989d11ea6c855c809f0b/docs/TransactionsApi.md#get_transactions)), this should be optional, but the functions that implement them have a required `i64` argument rather than an optional `Option<i64>` argument (e.g. [transactions_api.get_transactions](https://github.com/doy/ynab-api/blob/4c94e5f9101c14bfc5c6989d11ea6c855c809f0b/src/apis/transactions_api.rs#L93)).

In addition, there are various other arguments with the same problem.  For example, the aforementioned `get_transactions` should also have optional `since_date` and `_type` arguments.

I'm happy to submit a PR that fixes this, but given that the code is auto-generated, is that something you would want?  Is there any appetite for maintaining a delta from the autogen code?

It looks like the underlying problem is a [bug in the OpenAPI generator](https://github.com/OpenAPITools/openapi-generator/issues/3052).

**Comment by doy** [comment]
yeah, i'm not super interested in manually maintaining patches on top of the autogenerated code, and would overall prefer to just wait for that bug to be fixed (it looks like this might be soon? https://github.com/OpenAPITools/openapi-generator/pull/4016). if you can think of a way to automate the patching process (so that i can continue to just run a single script to release new versions), i would potentially consider merging something like that, though.

**Comment by borsboom** [comment]
Understandable, and it does look like OpenAPITools/openapi-generator#4016 fixes this, at least for my use case.

For the moment, I've made a fork that I generated using a [patched version of openapi-generator](https://github.com/borsboom/openapi-generator/tree/fixes) that includes the above PR as well as a couple of other things: https://github.com/borsboom/ynab-api/commit/0c83a52e098796cc133852f8ae95c55d13f3f5fd

Another problem I found and patched is that enums aren't exported from the crate, which I have opened OpenAPITools/openapi-generator#4079 for.

**Comment by doy** [comment]
awesome, yeah, the enum thing was bothering me too. once https://github.com/OpenAPITools/openapi-generator/pull/4016 is released, i'll regenerate everything and make a new release.

**Comment by borsboom** [comment]
FYI: I've opened a PR against openapi-generator to derive more common standard traits for the structs and enums: https://github.com/OpenAPITools/openapi-generator/pull/4142

**Comment by doy** [comment]
released version `3.0.0` with the new fixes for optional arguments - thanks for the work here!
